FROM php:8.2-cli

# Copie tous les fichiers dans le conteneur
COPY . /app
WORKDIR /app

# Expose le port utilisé par le serveur PHP
EXPOSE 10000

# Commande de démarrage
CMD ["php", "-S", "0.0.0.0:10000", "-t", "."]
